"""Identity — one canonical id, app-generated, store-independent.

The id is a full UUID string generated by the app (never a Mongo ObjectId), so
records stay valid across stores and machines. 122 random bits => collisions are
practically impossible. Never derive a shorter handle and store it — a stored
value derived from the id drifts out of sync; compute it on read if ever needed.
"""

from __future__ import annotations

import uuid


def new_id() -> str:
    """Return a fresh canonical id (UUID4 as a string)."""
    return str(uuid.uuid4())
